### PR TITLE
adds MNIST data to use in practical ML tasks

### PR DESCRIPTION
**Pull request by SnShine**

### CODE REVIEW

**Comment by ctjoreilly** [comment]
Could you add a note to the README indicating where the MNIST data originated from originally, e.g.:

http://yann.lecun.com/exdb/mnist/

**Comment by SnShine** [comment]
Yeah, I am adding a txt file in MNIST/ similar to other txt files in the repo.

**Comment by ctjoreilly** [comment]
Should the files not have .gz extension at the end of their names (as the sizes relate to the gzipped size) - or are these not just showing up in the list of files added?

**Comment by SnShine** [comment]
My bad, I have upzipped the files and uploaded to GitHub.
Is this looking fine, now?

**Comment by ctjoreilly** [comment]
I think its fine to have the unzipped versions in Github, this pull request has been merged already.

**Pull request merged**
